version: '3.8'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tu_base_de_datos
      MYSQL_USER: tu_usuario
      MYSQL_PASSWORD: tu_contraseña
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    environment:
      DATABASE_HOST: database
      DATABASE_USER: user
      DATABASE_PASSWORD: user_password
      DATABASE_NAME: my_database
    ports:
      - "5000:5000"
    depends_on:
      - database

volumes:
  db_data:
