name: Build, Push Docker image and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image to Docker Hub 
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: gonzagomezp1/backend:latest
        cache-from: type=registry,ref=gonzagomezp1/backend:cache
        cache-to: type=registry,ref=gonzagomezp1/backend:cache,mode=max

    - name: Logout from Docker Hub
      run: docker logout

    - name: Verify Docker image in local cache
      run: docker images gonzagomezp1/backend:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: frontend-430223

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: echo Y | gcloud auth configure-docker gcr.io

    - name: Tag Docker image for Google Container Registry
      run: docker tag gonzagomezp1/backend:latest gcr.io/frontend-430223/backend:latest

    - name: Push Docker image to Google Container Registry
      run: docker push gcr.io/frontend-430223/backend:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud config set run/region us-central1
        gcloud run deploy backend-service \
          --image gcr.io/frontend-430223/backend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --quiet
